(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.nehaBg = function() {
	this.initialize(img.nehaBg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1067,275);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiteEllipse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.8)","#FFFFFF"],[0,1],152.1,56,197.7,44.4).s().de(-260.5,-287.5,521,575);
	this.shape.setTransform(-0.8,268.9,1.217,0.942,0,0,0,-0.7,285.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiteEllipse, new cjs.Rectangle(-317.1,-270.7,634.3,541.4), null);


(lib.whiteBar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().dr(-485,-40.5,970,81);
	this.shape.setTransform(485,40.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiteBar, new cjs.Rectangle(0,0,970,81), null);


(lib.vodafoneCegcsoport = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F1001B").s().p("ABcA0IgIgDIACgIQAIAFAIAAQAQAAAAgQIAAgFQgGAGgIAAQgLAAgGgIQgGgIAAgNQAAgLAGgIQAIgIAMAAQAKAAAJADIAAA0QAAAMgHAGQgIAFgJAAQgFAAgFgBgABggPQgGAHgBALQABAHACAFQADAIAKAAQAJAAAEgGIAAgiQgFgBgGAAQgGAAgFADgAEjA0IAAhMIAIAAIAAAEQAHgFAIAAQAJAAAFAEQAFAFACAHIABALQAAAJgFAIQgDAHgHADIgLADQgGAAgFgCIAAAWgAE4gSQgGAAgHAFIAAAjQAEACAFAAQAJABAGgIQAFgGAAgJQAAgIgFgHQgEgFgGAAIgBAAgAG9ASIAAgjIgKAAIAAgHIAKAAIAAgPIAIAAIAAAPIANAAIAAAHIgNAAIAAAjQgBAGAGAAQADAAAFgDIACAHQgGAEgFAAQgMAAAAgOgAFeAWQgFgIAAgMQAAgHACgHQAHgNAPAAQAJAAAFAEQAGAGACAGQACAGAAAGQAAAIgDAHQgIAOgNAAQgMAAgHgKgAFngPQgHAHABAKQAAAHACAGQAEAJAKAAQAFAAAEgEQAHgFAAgNQAAgFgCgFQgFgKgJAAQgGAAgEADgADuAWQgHgIAAgMQAAgHAEgHQAGgNAPAAQAIAAAGAEQAFAGADAGQACAGAAAGQAAAIgEAHQgGAOgOAAQgMAAgGgKgAD2gPQgGAHgBAKQAAAHACAGQAFAJAKAAQAFAAAEgEQAHgFAAgNQAAgFgDgFQgEgKgJAAQgGAAgEADgAC7AZIADgHQAHAGAIAAQAMAAAAgIQAAgGgOgGQgPgEAAgKQAAgHAFgEQAFgEAHAAQAMAAAGAGIgDAGQgGgFgJAAQgIAAgBAHQAAAFANAFQAPAFAAALQAAAIgGAFQgFAEgIAAQgMAAgGgHgACRAZQgIgJAAgNQAAgKAEgHQAEgHAGgCQAFgCAFAAQANgBAHAMIgGAEQgFgIgJAAQgIAAgEAGQgFAHACAIQAAAKAEAGQAFAFAHAAQAJAAAGgGIACAIQgGAGgMAAQgKAAgGgHgAAhAYQgGgIgBgOQAAgIAEgHQAHgMANAAQAJAAAFAEQAFADACAIQACAHAAAFIgmAAQAAAWARAAQAKAAAGgGIADAHQgHAHgMAAQgMAAgHgIgAAygSQgLAAgEAOIAdAAQgBgHgFgEQgDgDgEAAIgBAAgAgOAZQgIgJAAgNQAAgKAEgHQAFgHAFgCQAFgCAEAAQAOgBAGAMIgHAEQgEgIgJAAQgGAAgFAGQgEAHABAIQAAAKAFAGQAEAFAHAAQAIAAAGgGIADAIQgHAGgLAAQgJAAgHgHgAhdAYQgHgIAAgOQAAgIAEgHQAGgMAOAAQAJAAAEAEQAGAEABAHQADAHAAAFIgnAAQAAAWASAAQAIAAAIgGIACAHQgFAHgNAAQgMAAgHgIgAhMgSQgMAAgDAOIAcAAQABgHgGgEQgEgDgDAAIgBAAgAjRAWQgGgIAAgMQAAgHAEgHQAFgNAPAAQAJAAAGAEQAGAGACAGQACAHAAAFQAAAHgEAIQgGAOgPAAQgMAAgGgKgAjJgPQgFAHgBAKQAAAHADAGQAEAJAJAAQAGAAAEgEQAGgGAAgMQAAgFgBgFQgFgKgKAAQgGAAgEADgAkhAbQgGgFAAgIQAAgIAGgFQAGgDAIgBIAMgCIAAAAQAAgNgLAAQgIAAgHAFIgDgGQAIgGAKAAQATAAAAAUIAAAjIgHAAIgBgFQgFAHgJAAQgHAAgFgFgAkeAOQAAAEACACQADAEAGAAQAFAAAHgGIAAgRQgXABAAAMgAlYAXQgGgIAAgNQAAgIAEgHQAHgMAOAAQAHAAAFACIAAgXIAJAAIAABMIgIAAIgBgEQgGAGgIAAQgKAAgHgJgAlPgPQgGAHgBALQAAAHADAFQAEAJAKAAQAHAAAFgGIAAgiQgFgCgFAAQgHAAgFADgAmRAWQgGgIAAgMQAAgHADgHQAGgNAQAAQAIAAAFAEQAHAGABAGQACAGABAGQAAAIgEAHQgHAOgNAAQgMAAgHgKgAmJgPQgGAHAAAKQAAAHACAGQAFAJAKAAQAFAAAEgEQAGgFABgNQAAgFgDgFQgEgKgJAAQgHAAgEADgAGUAeIAAg2IAHAAIABAGQAIgHAHAAIAEAAIgBAIIgEAAQgGAAgIAHIAAAogAh3AeIAAghQAAgPgMAAQgIAAgIAGIAAAqIgIAAIAAg2IAHAAIABAEQAHgFAKAAQALAAAEAFQAEAFAAAMIAAAhgAjvAeIAAgvIgIAAIAAgHIAIAAIAAgEQgBgLAFgFQAFgEAHAAIAJACIgBAHIgHgBQgJAAAAAMIAAAEIAMAAIAAAHIgMAAIAAAvgAm5AeIgahMIAKAAIAVA+IAVg+IAJAAIgaBMgAAngkIATgQIAFAGIgUAOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.vodafoneCegcsoport, new cjs.Rectangle(-46.8,-5.3,93.6,10.6), null);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7C7D7D").s().p("AgvA/QgSgXAAgnQAAgnASgXQASgXAdAAQAeAAASAXQASAXAAAnQAAAngSAXQgRAWgfAAQgeAAgRgWgAgPgiQgHAOAAAVQAAAVAHAOQAGAMAJAAQAKAAAGgNQAHgNAAgVQAAgVgHgOQgGgOgKAAQgJAAgGAOg");
	this.shape.setTransform(87.8,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7C7D7D").s().p("AgiBUQgJAAgGgFQgGgFAAgIQAAgNALgPQAHgLAQgQIAXgWQALgNAAgIQAAgPgNAAQgHAAgMAHQgHAFgGAAQgIAAgGgGQgFgGAAgHQAAgLAKgHQATgMAWAAQAaAAAPAOQAPANAAAZQAAATgPAQQgGAIgcAaIgKAKIAmAAQAJABAGAFQAGAFAAAIQAAAIgGAFQgGAFgJAAg");
	this.shape_1.setTransform(75.1,17.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7C7D7D").s().p("AAIBOQgGgFAAgIIAAgSIguAAQgJAAgGgFQgGgFAAgIQAAgHADgGQAVgqApguQAKgLALAAQAJAAAFAGQAGAFAAAIQAAAIgHAHQggAggRAbIARAAIAAgLQAAgIAGgGQAGgFAJAAQAJAAAGAFQAGAGAAAIIAAALIABAAQAJAAAGAGQAGAFAAAIQAAAIgGAFQgGAFgJAAIgBAAIAAASQAAAIgGAFQgGAGgJAAQgJAAgGgGg");
	this.shape_2.setTransform(62.4,17.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#7C7D7D").s().p("AADBOQgFgFAAgIIAAheIgHAEQgFADgFAAQgJAAgFgGQgFgFAAgIQAAgMAJgFIAhgVQAHgEAHAAQAJAAAGAFQAGAGAAAIIAACBQAAAIgGAFQgHAGgIAAQgJAAgGgGg");
	this.shape_3.setTransform(51.1,17.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#7C7D7D").s().p("AgOA5QgGgFAAgHIAAgIQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIIAAAIQAAAHgGAFQgGAGgJAAQgIAAgGgGgAgOgWQgGgGAAgIIAAgHQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIIAAAHQAAAIgGAGQgGAFgJAAQgIAAgGgFg");
	this.shape_4.setTransform(39,19.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#7C7D7D").s().p("AgOARQgGgFAAgIIAAgHQAAgIAGgFQAGgFAIgBQAJABAGAFQAGAFAAAIIAAAHQAAAIgGAFQgGAFgJAAQgIAAgGgFg");
	this.shape_5.setTransform(33,23.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7C7D7D").s().p("AgeArIAAhxQAAgHAGgGQAGgFAJgBQAJABAFAFQAGAGAAAHIAABrQAAAKACABIAGADQAMAFAAANQAAAJgHAGQgHAFgKAAQglAAAAgug");
	this.shape_6.setTransform(27.1,16.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7C7D7D").s().p("AgnAvQgQgRAAgeQAAgbAQgRQARgSAaAAQAWAAAPAMQAPAMAAATQABAihCACQADALAMAAQAGAAAOgIQAHgEAFAAQAIAAAFAGQAFAGAAAIQAAAKgKAGQgRALgaAAQgZAAgRgQgAgMgMQAZgBAAgHQAAgHgJAAQgLAAgFAPg");
	this.shape_7.setTransform(17.4,19.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#7C7D7D").s().p("AgfAgIAAgnIgCAAQgJAAgFgHQgFgEAAgIQAAgIAFgFQAFgFAJAAIACAAIAAgQQAAgHAGgGQAGgFAJgBQAJABAFAFQAGAGAAAHIAAAQIAOAAQAJAAAFAEQAGAGAAAIQAAAIgGAFQgFAFgJABIgOAAIAAAlQAAAJAGAAIAIgBQAGgCAEAAQAIAAAFAGQAGAFAAAIQAAAMgMAGQgKAHgSAAQgsAAAAgwg");
	this.shape_8.setTransform(6.8,18);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol22, new cjs.Rectangle(0,0,96.9,34.2), null);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7C7D7D").s().p("AgOBOQgGgFAAgIIAAgIQAAgIAGgFQAGgFAIAAQAJAAAGAFQAGAFAAAIIAAAIQAAAIgGAFQgGAGgJAAQgIAAgGgGgAgOAaQgGgFAAgIIAAhNQAAgIAGgGQAGgFAIAAQAJAAAGAFQAGAGAAAIIAABNQAAAIgGAFQgGAFgJAAQgIAAgGgFg");
	this.shape.setTransform(56,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7C7D7D").s().p("AgfAgIAAgnIgCAAQgJAAgFgHQgFgEAAgIQAAgIAFgFQAFgFAJAAIACAAIAAgQQAAgHAGgGQAGgFAJgBQAJABAFAFQAGAGAAAHIAAAQIAOAAQAJAAAFAEQAGAGAAAIQAAAIgGAFQgFAFgJABIgOAAIAAAlQAAAJAGAAIAIgBQAGgCAEAAQAIAAAFAGQAGAFAAAIQAAAMgMAGQgKAHgSAAQgsAAAAgwg");
	this.shape_1.setTransform(47.8,18);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7C7D7D").s().p("AgtA0QgHgGAAgJQAAgIAFgFQAGgGAIAAQAEAAALAFQAOAFAIAAQAGAAAAgEQAAgDgJgDIgVgGQgOgFgGgHQgHgIAAgPQAAgRANgLQAOgLAUAAQAWAAANAFQAOAGAAANQAAAIgFAFQgGAFgIAAQgEAAgIgDQgLgEgHAAQgEAAAAADQAAAEAGACIATAFQAQAFAIAHQAIAHAAAQQAAASgPALQgPAMgXAAQgfAAgOgLg");
	this.shape_2.setTransform(37.7,19.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#7C7D7D").s().p("AgpAtQgRgSAAgbQAAgaARgSQAQgRAZAAQAaAAARARQAQASAAAaQAAAcgQARQgQASgbAAQgZgBgQgRgAgKgRQgFAGAAALQAAALAFAIQAEAGAGABQAIgBAEgGQAEgIAAgLQAAgKgEgHQgFgIgHABQgGgBgEAIg");
	this.shape_3.setTransform(26.2,19.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#7C7D7D").s().p("AAuA4QgGgFAAgIIAAg3QAAgGgCgDQgCgDgHAAQgFAAgDABIAAAIIAAA6QAAAIgGAFQgGAGgJAAQgIAAgGgGQgGgFAAgIIAAg3QAAgMgKAAQgFAAgEABIAABCQAAAIgGAFQgGAGgJAAQgJAAgGgGQgGgFAAgIIAAhUQAAgIAFgFQAFgGAJAAQAHABAHAEQAKgGAMAAQAUAAAKAIQANgIARAAQAwAAAAAuIAAA6QAAAIgGAFQgGAGgJAAQgJAAgGgGg");
	this.shape_4.setTransform(11.1,19.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol21, new cjs.Rectangle(0,0,61.5,34.2), null);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7C7D7D").s().p("AARA4QgHgFAAgIIAAg2QAAgIgCgDQgCgCgGAAIgKABIAABCQAAAIgGAFQgGAGgJAAQgJAAgGgGQgGgFAAgIIAAhUQAAgIAFgFQAFgGAJAAQAIAAAGAEQAKgFANAAQAxAAAAAwIAAA4QAAAIgHAFQgFAGgKAAQgIAAgGgGg");
	this.shape.setTransform(113.7,19.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#7C7D7D").s().p("AgpBEQgRgSAAgbQAAgaARgSQAQgRAZAAQAaAAARARQAQASAAAaQAAAcgQARQgQASgbAAQgZAAgQgSgAgKAFQgFAHAAALQAAALAFAIQAEAHAGAAQAIAAAEgHQAEgHAAgMQAAgLgEgHQgFgGgHAAQgGAAgEAGgAALgyQgGgFAAgHIAAgGQAAgHAGgFQAFgFAIAAQAIAAAGAFQAFAFAAAHIAAAGQAAAHgFAFQgGAFgIAAQgIAAgFgFgAgkgyQgGgFAAgHIAAgGQAAgHAGgFQAFgFAIAAQAIAAAGAFQAFAFAAAHIAAAGQAAAHgFAFQgFAFgIAAQgIAAgGgFg");
	this.shape_1.setTransform(101.5,17.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#7C7D7D").s().p("AgdBtQgMgGAAgMQAAgIAEgFQAFgFAJAAIAMADQAFAAADgEQADgEAAgIIAAhlQAAgIAGgFQAGgGAJAAQAJAAAGAGQAGAFAAAIIAABhQAAAagPAQQgPAOgXAAQgLAAgHgDgAAGhJQgGgGAAgIIAAgGQAAgHAGgGQAGgFAJAAQAJAAAGAFQAGAGAAAHIAAAGQAAAIgGAGQgGAFgJAAQgJAAgGgFg");
	this.shape_2.setTransform(90.4,19.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#7C7D7D").s().p("AguBIQgOgRAAgcQAAgbARgRQAQgRAYAAIANABIAAgmQgBgHAHgGQAGgFAJAAQAJAAAGAFQAGAGAAAHIAAB6QAJAFAAAMQAAAJgGAGQgHAGgIAAQgLAAgIgGQgMAHgOAAQgbAAgOgSgAgMAJQgFAIAAAKQAAAbASAAQADAAAGgCIAAgxIgJgBQgHAAgGAHg");
	this.shape_3.setTransform(83.8,16.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#7C7D7D").s().p("AgpBKQgRgSAAgbQAAgaARgSQAQgRAZAAQAaAAARARQAQASAAAaQAAAcgQARQgQASgbAAQgZAAgQgSgAgKALQgFAHAAALQAAALAFAIQAEAHAGAAQAIAAAEgHQAEgHAAgMQAAgKgEgIQgFgHgHAAQgGAAgEAHgAAIgsQgEgGAAgGIABgIIAFgOQAGgNANAAQAHAAAGAFQAEAGAAAHQAAAEgCAGIgEALQgGAOgNAAQgIAAgFgGgAgogsQgFgGAAgGIACgIIAFgOQAFgNANAAQAIAAAFAFQAFAGAAAHQAAAEgDAGIgEALQgFAOgNAAQgIAAgFgGg");
	this.shape_4.setTransform(71.6,16.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#7C7D7D").s().p("AgeArIAAhxQAAgHAGgGQAGgFAJgBQAJABAFAFQAGAGAAAHIAABrQAAAKACABIAGADQAMAFAAANQAAAJgHAGQgHAFgKAAQglAAAAgug");
	this.shape_5.setTransform(62.7,16.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#7C7D7D").s().p("AAPBRIgYgiIAAAYQAAAIgGAFQgGAFgJAAQgJAAgGgFQgGgFAAgIIAAiNQAAgHAGgGQAGgFAJgBQAJABAGAFQAGAGAAAHIAABFIANgSQAFgHAEgCQAEgEAHAAQAIAAAGAGQAGAGAAAIQAAAHgHAHIgSAVQAQAOAOAWQADAEAAAHQAAAHgGAGQgFAHgJgBQgLABgGgJg");
	this.shape_6.setTransform(53.8,16.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7C7D7D").s().p("AgnAvQgRgRAAgeQAAgbARgRQARgSAaAAQAWAAAPAMQAQAMAAATQgBAihCACQAEALAMAAQAGAAAOgIQAHgEAGAAQAHAAAFAGQAFAGABAIQAAAKgLAGQgRALgaAAQgaAAgQgQgAgMgMQAZgBAAgHQAAgHgJAAQgLAAgFAPg");
	this.shape_7.setTransform(42,19.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#7C7D7D").s().p("AguBIQgOgRAAgcQAAgbARgRQAQgRAYAAIANABIAAgmQgBgHAHgGQAGgFAJAAQAJAAAGAFQAGAGAAAHIAAB6QAJAFAAAMQAAAJgGAGQgGAGgJAAQgLAAgHgGQgOAHgNAAQgbAAgOgSgAgMAJQgFAIAAAKQAAAbASAAQADAAAGgCIAAgxIgJgBQgIAAgFAHg");
	this.shape_8.setTransform(30.2,16.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#7C7D7D").s().p("AgoA4QgFgFgBgIIAAhUQABgIAFgFQAFgFAJgBQALAAAFAJQAKgKASAAQALAAAJAFQAIAGABALQAAAKgHAGQgFAFgJABIgKgDIgIgBQgMAAAAAZIAAAnQABAIgHAFQgGAGgIAAQgJAAgHgGg");
	this.shape_9.setTransform(19.9,19.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#7C7D7D").s().p("AgfByQgJAAgGgFQgGgFAAgIIAAiCQAAgIAGgFQAGgFAJAAIA8AAQAJAAAFAFQAFAFAAAIQAAAIgFAFQgFAFgJAAIgnAAIAAAaIAjAAQAJAAAFAFQAGAFAAAIQAAAIgGAFQgFAFgJAAIgjAAIAAAfIArAAQAJAAAGAGQAFAFAAAIQAAAIgFAFQgGAFgJAAgAghhEQgEgFAAgHQAAgKALgFIAkgQQAGgCAGAAQAHAAAFAFQAEAFAAAGQAAALgLAFIgnAQIgJACQgHAAgFgFg");
	this.shape_10.setTransform(8.6,14.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol20, new cjs.Rectangle(0,0,122.1,34.2), null);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("ALoCOQgLgKAAgOIAAjKIgpAAQgQAAgLgKQgLgJABgPQgBgOALgJQALgKAQAAICfAAQAQAAALAKQAKAJAAAOQAAAPgKAJQgLAKgQAAIgqAAIAADKQAAAOgLAKQgMAKgPAAQgQAAgLgKgAHzCYQgQAAgLgKQgLgJAAgPIAAjsQAAgOALgJQALgKAQAAIBuAAQAQAAAKAKQAJAIAAAPQAAAPgJAJQgKAKgQAAIhHAAIAAAvIBAAAQAQAAAKAKQAJAJAAAOQAAAOgJAKQgKAJgQgBIhAAAIAAA5IBPAAQAQAAAKAJQAJAJAAAPQAAAPgJAJQgKAKgQAAgAFzCYQgUAAgNgNQgQgPgcg5Igag4IAABrQgBAOgKAKQgMAKgQAAQgQAAgLgKQgLgKAAgOIAAjnQAAgOALgMQAKgMARAAIAFAAQAWABAOAOQAMAKAOAeQANAYAdBDIAAhwQAAgOALgKQALgKAQAAQAQAAALAKQALAKAAAOIAADoQAAAPgLAKQgKAMgRAAgABWB9QgQg1gMgVQgMgTgNAAIgHAAIAABWQAAAOgLAKQgLAKgPAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgKAQAAIA/AAQAxAAAbAaQAaAYAAAoQAAAwgqAVQAVASAUA7QAIATAAAJQAAAQgLALQgLAMgPAAQgeAAgIgbgAAagiIAaAAQAZAAAAgbQAAgXgZAAIgaAAgAjqCYQgRAAgLgKQgLgJABgPIAAjsQgBgOALgJQALgKARAAIBtAAQAQAAAKAKQAJAIAAAPQAAAPgJAJQgKAKgQAAIhHAAIAAAvIBAAAQARAAAJAKQAJAJAAAOQAAAOgJAKQgJAJgRgBIhAAAIAAA5IBPAAQARAAAJAJQAJAJAAAPQAAAPgJAJQgJAKgRAAgAmyCOQgLgKAAgOIAAjKIgpAAQgQAAgLgKQgLgJABgPQgBgOALgJQALgKAQAAICfAAQAQAAALAKQAKAJAAAOQAAAPgKAJQgLAKgQAAIgqAAIAADKQAAAOgLAKQgMAKgPAAQgQAAgLgKgApICYQgUAAgNgNQgQgPgcg5Igag4IAABrQAAAOgMAKQgKAKgRAAQgQAAgLgKQgLgKAAgOIAAjnQAAgOAKgMQAMgMAQAAIAFAAQAWABAOAOQAMAKAPAeQANAYAcBDIAAhwQAAgOALgKQALgKAQAAQAQAAALAKQALAKAAAOIAADoQAAAPgKAKQgMAMgQAAgAtsCOQgLgKAAgOIAAjrQAAgPALgJQALgKAQAAQAQAAAMAKQAKAJAAAPIAADrQAAAOgLAKQgLAKgQAAQgQAAgLgKg");
	this.shape.setTransform(88.8,15.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol19, new cjs.Rectangle(0,0,177.6,30.3), null);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("ABsCrQgegdAAgzIAAihQAAgPALgKQALgJAQAAQAQAAALAJQALAKAAAPIAAChQAAArAkAAQAkAAAAgrIAAihQAAgPALgKQAKgJARAAQAQAAALAJQALAKAAAPIAAChQAAAzgfAdQgeAeg0AAQgzAAgegegAzyCrQgPgNAAgQQAAgOAKgKQAKgLAPAAQANAAAPALQAVAQAOAAQAdAAAAgcQAAgMgTgKIgqgTQg8gfAAg2QAAglAdgZQAdgZAqABQAsAAAgAZQAPAMAAAQQAAAPgKAKQgKALgOAAQgOAAgMgJQgSgOgNAAQgKAAgGAGQgHAFAAAJQAAALATAJIAqASQA9AeAAA6QAAAqgeAaQgeAbgvgBQgtAAgmgdgATBC9QgLgLAAgOIAAjrQAAgOALgKQALgJAQAAQARAAALAJQAKAKAAAOIAADrQAAAOgLALQgLAJgQAAQgQAAgLgJgAQUC9QgLgLAAgOIAAjJIgoAAQgQAAgLgKQgLgKAAgOQAAgOALgKQALgJAQAAICeAAQARAAAKAJQALAKAAAOQAAAOgLAKQgKAKgRAAIgpAAIAADJQAAAOgLALQgMAJgQAAQgQAAgLgJgAMgDGQgRAAgKgJQgLgKAAgPIAAjrQAAgOALgKQAKgJARAAIBuAAQAQAAAJAJQAKAJAAAPQAAAOgKAKQgJAKgQAAIhIAAIAAAuIBBAAQAQAAAJAJQAKAJAAAOQAAAQgKAJQgJAJgQAAIhBAAIAAA4IBPAAQARAAAJAKQAKAJAAAOQAAAPgKAKQgJAJgRAAgAJQDGQgQAAgLgJQgLgKAAgPIAAjrQAAgOALgKQALgJAQAAQARAAALAJQALAKAAAOIAADKIBMAAQAQAAALAKQAMAKAAANQAAAPgMAKQgLAJgQAAgAFkDGQgRAAgLgLQgKgMAAgPQAAgJAFgLQAjhHBKhqIhMAAQgQAAgLgKQgLgKAAgOQAAgOALgKQALgJAQAAICKAAQARAAALALQAKALAAAPQAAANgSAcIhlCdIBSAAQAQAAALAKQALAKAAANQAAAPgLAKQgLAJgQAAgAivDGQgQAAgLgJQgLgKAAgPIAAjrQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAADKIBNAAQAQAAALAKQALAKAAANQAAAPgLAKQgLAJgQAAgAlFC9QgLgLAAgOIAAjrQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAADrQAAAOgLALQgLAJgQAAQgQAAgLgJgAoZDGQgQAAgLgJQgLgLAAgOIAAjrQAAgOALgKQAKgJARAAIAyAAQA0AAAdAXQAcAXAAAqQAAAggbAUQASAKALATQAKATAAAUQAAAugfAYQggAYg6AAgAnzCDIAMAAQArAAAAgbQAAgaghAAIgWAAgAnzALIASAAQAaAAAAgYQAAgOgIgGQgHgEgTAAIgKAAgAqeCpIgKggIhXAAIgKAgQgJAdgdAAQgPAAgLgLQgLgMAAgPQAAgGADgJQA0ikAhhBQAJgUAgAAQAeAAAKAUQAcA3A5CuQADAJAAAGQAAAPgLAMQgLALgQAAQgcAAgJgdgAq/BHIgUg+IgWA+IAqAAgAvbC9QgLgLAAgOIAAjJIgoAAQgQAAgLgKQgLgKAAgOQAAgOALgKQALgJAQAAICeAAQARAAAKAJQALAKAAAOQAAAOgLAKQgKAKgRAAIgpAAIAADJQAAAOgLALQgMAJgQAAQgQAAgLgJgADRiKQgKgIAAgOIAAgJQAAgNAKgKQAJgIAPAAQAPAAAKAIQAKAKAAANIAAAJQAAAOgKAIQgKAJgPAAQgPAAgJgJgAB6iKQgKgIAAgOIAAgJQAAgNAKgKQAKgIAOAAQAPAAAKAIQAKAKAAANIAAAJQAAAOgKAIQgJAJgPAAQgOAAgLgJg");
	this.shape.setTransform(128.2,20.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol18, new cjs.Rectangle(0,0,256.5,40.2), null);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("ASkDaQgLgKAAgPQAAgNAIgNQAHgMAAgPQAAgPAKgLQALgKAQAAQAPAAALAKQALAKAAAQIAAADQAAApgVAaQgOASgRAAQgPAAgLgKgAOcCPQgngsAAhBQAAhBAmgsQAngtA7AAQA7AAAmAsQAnAsAABCQAABCgnAsQgmArg7AAQg6AAgngsgAPTgcQgRAaAAAkQAAAkARAaQARAZAZAAQAZAAAQgZQARgZAAglQAAglgRgaQgQgYgZAAQgZAAgRAZgAqbCQQgogsAAhCQAAhBApgsQAqgtA9AAQAsAAAlAUQAZANAAAUQAAAPgLAKQgJAKgNAAQgOAAgLgHQgXgOgZAAQgcAAgTAZQgTAaAAAkQAAAlASAZQASAZAaAAQAWAAANgGIAAgaQAAgMgLAAIgLAAQgQAAgKgJQgLgJAAgOQAAgPALgKQAKgKAQAAIAgAAQAmAAAOANQAOANAAAjIAABAQAAAVgUAKQgrAVgwAAQg8AAgogrgALjCvQgLgKAAgOIAAjKIgoAAQgQAAgLgJQgLgKAAgPQAAgOALgJQALgJAQAAICeAAQARAAAKAJQALAJAAAOQAAAPgLAKQgKAJgRAAIgpAAIAADKQAAAOgLAKQgMAKgQAAQgQAAgLgKgAJJCcIgKggIhXAAIgKAgQgJAdgdAAQgPAAgLgLQgLgMAAgPQAAgGADgKQA0ijAhhBQAJgUAgAAQAeAAAKAUQAcA3A5CtQADAKAAAGQAAAPgLAMQgLALgQAAQgcAAgJgdgAIoA6IgUg9IgWA9IAqAAgAE+CvQgLgKAAgOIAAhbIhIAAIAABbQAAAOgLAKQgLAKgQAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAABOIBIAAIAAhOQAAgOALgKQALgJAQAAQARAAAKAJQALAKAAAOIAADrQAAAOgLAKQgKAKgRAAQgQAAgLgKgAgmC5QgRAAgLgMQgLgLAAgPQAAgJAGgLQAjhHBJhrIhLAAQgRAAgLgJQgKgKAAgPQAAgOAKgJQALgJARAAICIAAQARAAALALQALALAAAPQAAANgTAcIhkCdIBSAAQAQAAALAKQALAJAAAOQAAAPgLAJQgLAKgQAAgAilCvQgLgKAAgOIAAjrQAAgOALgKQALgJARAAQAQAAALAJQAKAKAAAOIAADrQAAAOgLAKQgKAKgQAAQgRAAgLgKgAl6C5QgQAAgMgKQgLgKAAgOIAAjsQAAgOALgJQALgJAQAAIAyAAQA1AAAcAXQAdAXAAAqQAAAggbATQASAKAKAUQAKATAAAUQAAAugfAYQgfAYg7AAgAlUB2IALAAQAsAAAAgbQAAgaghAAIgWAAgAlUgBIASAAQAZAAAAgZQAAgOgHgGQgIgFgSAAIgKAAgAtrC5QgRAAgKgKQgLgJAAgPIAAjsQAAgOALgJQAKgJARAAIBuAAQAQAAAJAJQAKAJAAAOQAAAPgKAKQgJAJgQAAIhIAAIAAAvIBBAAQAQAAAJAJQAKAJAAAOQAAAPgKAKQgJAJgQAAIhBAAIAAA4IBPAAQARAAAJAKQAKAJAAAOQAAAPgKAJQgJAKgRAAgAwBCaIgLhtIgfBoQgEAMgLAIQgLAIgNAAIgCAAQgOAAgLgIQgLgIgDgMIgfhoIgMBtQgDAfgkAAQgQAAgKgJQgKgKAAgPIAZjpQABgPAMgLQALgJAPAAIAEAAQAaAAANATQATAbAgBuQAfhsATgdQANgTAaAAIAEAAQAPAAALAJQAMALACAPIAZDpQAAAPgKAKQgLAJgQAAQgjAAgEgfgAPAiSQgIgIAAgNQAAgTAUgJIBDgcQAKgEALAAQANAAAJAJQAIAJAAAMQAAATgVAJIhIAeIgPACQgOAAgIgJgAjGiSQgJgIAAgNQAAgTAVgJIBDgcQAKgEALAAQANAAAIAJQAJAJAAAMQAAATgVAJIhIAeIgPACQgOAAgIgJg");
	this.shape.setTransform(126.6,22.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol17, new cjs.Rectangle(0,0,253.3,45.6), null);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AJ5BuQgngtAAhAQAAhBAmgtQAngsA7AAQA7AAAmArQAnAtAABCQAABCgnAsQgmArg7AAQg6AAgngsgAKwg9QgRAZAAAlQAAAkARAaQARAYAZAAQAZAAAQgYQARgZAAglQAAglgRgaQgQgZgZABQgZgBgRAagAGHB8QgQgNAAgQQAAgNAKgLQALgLAOAAQANAAAPAMQAWAPANAAQAeAAAAgcQAAgLgUgKIgpgTQg9geAAg4QAAglAdgZQAdgYArAAQArAAAhAZQAPAMAAAQQAAAQgKAJQgKALgPAAQgOAAgLgJQgTgOgMABQgKAAgHAFQgGAGAAAIQAAALATAKIApASQA9AdAAA6QAAAqgeAbQgeAagvAAQgtAAglgegAWRCOQgLgKAAgOIAAgOQAAgOALgLQALgJAQAAQARAAALAJQALALAAAOIAAAOQAAAOgLAKQgLAKgRgBQgQABgLgKgAUqB6IgKgfIhXAAIgKAfQgJAdgdAAQgPAAgLgLQgLgLAAgQQAAgFADgKQA0ijAhhCQAJgTAgAAQAeAAAKATQAcA3A5CuQADAKAAAFQAAAQgLALQgLALgQAAQgcAAgJgdgAUJAYIgUg9IgWA9IAqAAgAQfCOQgLgKAAgOIAAhbIhIAAIAABbQAAAOgLAKQgLAKgQgBQgQABgLgKQgLgKAAgOIAAjsQAAgOALgJQALgJAQAAQAQAAALAJQALAJAAAOIAABOIBIAAIAAhOQAAgOALgJQALgJAQAAQARAAAKAJQALAJAAAOIAADsQAAAOgLAKQgKAKgRgBQgQABgLgKgACNCOQgLgKAAgOIAAjKIgpAAQgQAAgKgKQgLgJAAgPQAAgOALgJQAKgJAQAAICfAAQAQAAALAJQAKAJAAAOQAAAPgKAJQgLAKgQAAIgqAAIAADKQAAAOgLAKQgLAKgQgBQgQABgLgKgAhnCXQgQABgLgKQgLgKAAgOIAAjsQAAgOALgJQALgJAQAAIBtAAQAQAAAKAJQAJAJAAAOQAAAPgJAJQgKAKgQAAIhGAAIAAAvIBAAAQAPAAAKAJQAJAKAAAOQAAAOgJAKQgKAIgPABIhAAAIAAA4IBOAAQAQAAAKAJQAJAKAAAOQAAAPgJAJQgKAKgQgBgAjmCXQgVAAgNgMQgQgPgcg5Igag4IAABrQAAAOgLAKQgLAKgRgBQgQABgLgKQgLgKAAgOIAAjnQAAgPALgLQALgLAQAAIAGAAQAVgBAPAOQALALAPAeQANAYAcBDIAAhwQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAADnQAAAPgKALQgLALgRAAgAoEB9QgQg1gMgVQgLgTgOAAIgHAAIAABWQAAAOgLAKQgLAKgQgBQgQABgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAIBBAAQAwgBAbAaQAbAZAAAoQAAAugrAWQAVASAVA7QAHATAAAJQAAAQgLALQgLAMgPgBQgeAAgIgagApAghIAbAAQAYAAAAgcQAAgXgYAAIgbAAgAtFCXQgRABgKgKQgLgKAAgOIAAjsQAAgOALgJQAKgJARAAIBuAAQAQAAAJAJQAKAJAAAOQAAAPgKAJQgJAKgQAAIhIAAIAAAvIBBAAQAQAAAJAJQAKAKAAAOQAAAOgKAKQgJAIgQABIhBAAIAAA4IBPAAQARAAAJAJQAKAKAAAOQAAAPgKAJQgJAKgRgBgAwNCOQgLgKAAgOIAAjKIgpAAQgQAAgKgKQgLgJAAgPQAAgOALgJQAKgJAQAAICfAAQAQAAALAJQAKAJAAAOQAAAPgKAJQgLAKgQAAIgqAAIAADKQAAAOgLAKQgLAKgQgBQgQABgLgKgAyiCXQgVAAgNgMQgQgPgcg5Igag4IAABrQAAAOgLAKQgLAKgRgBQgQABgLgKQgLgKAAgOIAAjnQAAgPALgLQALgLAQAAIAGAAQAVgBAPAOQALALAPAeQANAYAcBDIAAhwQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAADnQAAAPgKALQgLALgRAAgA3HCOQgLgKAAgOIAAjsQAAgOALgJQALgJAQAAQARAAALAJQAKAJAAAOIAADsQAAAOgLAKQgLAKgQgBQgQABgLgKgAWRAvQgLgKAAgOIAAiLQAAgPALgKQALgJAQAAQARAAALAJQALAKAAAPIAACLQAAAOgLAKQgLAKgRAAQgQAAgLgKg");
	this.shape.setTransform(153.4,29.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol16, new cjs.Rectangle(4.4,14.4,298.2,30.8), null);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AgCCrQgfgdAAgzIAAihQABgPAKgKQAMgJAPAAQAQAAAKAJQAMAKAAAPIAAChQAAArAkAAQAjAAABgrIAAihQAAgPALgKQAKgJARAAQAPAAAMAJQALAKgBAPIAAChQAAAzgeAdQgeAeg0AAQgzAAgdgegARSC9QgLgLAAgOIAAjrQAAgOALgKQALgJAQAAQARAAALAJQAKAKAAAOIAADrQAAAOgLALQgLAJgQAAQgQAAgLgJgAOlC9QgLgLAAgOIAAjJIgoAAQgQAAgLgKQgLgKAAgOQAAgOALgKQALgJAQAAICeAAQAQAAALAJQALAKAAAOQAAAOgLAKQgLAKgQAAIgpAAIAADJQgBAOgKALQgMAJgQAAQgQAAgLgJgAKwDGQgQAAgLgJQgKgKgBgPIAAjrQABgOAKgKQALgJAQAAIBvAAQAPAAAKAJQAKAJAAAPQAAAOgKAKQgKAKgPAAIhIAAIAAAuIBBAAQAQAAAJAJQAKAKAAAOQAAAPgKAJQgJAJgQAAIhBAAIAAA5IBPAAQAQgBAKAKQAKAJgBAOQABAPgKAKQgKAJgQAAgAHhDGQgQAAgLgJQgLgKAAgPIAAjrQAAgOALgKQALgJAQAAQARAAAKAJQAMAKAAAOIAADLIBMAAQAQgBALAKQAMAKgBANQABAPgMAKQgLAJgQAAgAD1DGQgRAAgLgLQgKgMAAgPQAAgJAFgLQAjhHBKhqIhMAAQgRAAgLgKQgKgKAAgOQAAgOAKgKQALgJARAAICJAAQASAAALAMQAKAKAAAPQAAANgSAcIhlCeIBSAAQAQgBALAKQALAKAAANQAAAPgLAKQgLAJgQAAgAk7DGQgRAAgLgLQgFgGgCgGQgDAHgGAFQgLALgPAAQgcAAgJgdIgKggIhYAAIgJAgQgKAdgcAAQgPAAgLgLQgLgMAAgPQAAgGADgKQA0ijAghBQAKgUAgAAQAeAAAKAUQAcA3A5CtIAAABIACgFQAjhHBKhqIhMAAQgQAAgLgKQgLgKAAgOQAAgOALgKQALgJAQAAICJAAQARAAALAMQALAKAAAPQAAANgTAcIhkCeIBSAAQAQgBALAKQALAKAAANQAAAPgLAKQgLAJgQAAgAnHBHIgVg+IgVA+IAqAAgAtTDGQgQAAgLgJQgLgKAAgPIAAjrQAAgOALgKQALgJAQAAIBuAAQAQAAAJAJQAKAJAAAPQAAAOgKAKQgJAKgQAAIhHAAIAAAuIBAAAQAQAAAKAJQAJAKAAAOQAAAPgJAJQgKAJgQAAIhAAAIAAA5IBOAAQARgBAJAKQAKAJAAAOQAAAPgKAKQgJAJgRAAgAxtDGQgPAAgLgJQgLgLAAgOIAAjrQAAgOALgKQALgJAPAAIBJAAQA+AAAnArQAoAqAABCQAABDgoAqQgoAqg9AAgAxGCEIAiAAQAcAAASgXQARgYAAgmQAAgmgRgXQgSgXgcAAIgiAAgABiiJQgKgKAAgNIAAgKQAAgNAKgIQAJgJAPAAQAOAAAKAJQAKAIAAANIAAAKQAAANgKAKQgKAIgOAAQgPAAgJgIgAALiJQgLgKAAgNIAAgKQAAgNAKgIQALgJAOAAQAPAAAKAJQAKAIAAANIAAAKQAAANgKAKQgJAIgPAAQgPAAgKgIg");
	this.shape.setTransform(121.5,25.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol15, new cjs.Rectangle(4.4,5.1,234.2,40.2), null);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AcbDaQgLgKAAgPQAAgNAIgNQAHgMAAgPQAAgPAKgLQALgKAQAAQAPAAALAKQALAKAAAQIAAADQAAApgVAaQgOASgRAAQgPAAgLgKgAUUCPQgngsAAhBQAAhBAngsQAngtA6AAQA7AAAnAsQAmAsAABCQAABCgmAsQgnArg7AAQg6AAgngsgAVMgcQgRAaAAAkQAAAkARAaQARAZAYAAQAZAAARgZQARgZAAglQAAglgRgaQgRgYgZAAQgYAAgRAZgAMnCPQgngsAAhBQAAhBAngsQAngtA6AAQA7AAAnAsQAmAsAABCQAABCgmAsQgnArg7AAQg6AAgngsgANfgcQgRAaAAAkQAAAkARAaQARAZAYAAQAZAAARgZQARgZAAglQAAglgRgaQgRgYgZAAQgYAAgRAZgAI1CdQgPgMAAgQQAAgOAKgLQAKgLAPAAQANAAAPAMQAVAQAOAAQAdAAAAgcQAAgMgTgKIgqgTQg8gfAAg2QAAglAdgZQAdgZAqAAQAsAAAgAZQAPAMAAARQAAAPgKAKQgKAKgOAAQgOAAgMgIQgSgOgNAAQgKAAgGAFQgHAGAAAJQAAALATAJIAqASQA9AdAAA7QAAApgeAbQgeAagvAAQgtAAgmgegAFJCPQgngsAAhBQAAhBApgtQApgsA9AAQAhAAAcAKQAUAHALAJQAPAMAAAPQAAAOgKALQgKAKgPAAQgNAAgOgJQgRgMgcAAQgcAAgTAZQgTAZAAAlQAAAlASAZQASAZAaAAQAXAAAbgPQALgIAMAAQAPAAAKALQAKAKAAAOQAAAVgUALQgrAWgtAAQg8AAgogsgAa2CpQgwg8gegbIAABFQAAAOgLAKQgLAKgRAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQARAAALAJQALAKAAAOIAAA0IA+hDQASgSASAAQAPAAALAKQAJALAAAOQAAAQgOAOIhQBMQA+AyAlAyQAKANAAAMQAAAPgKAKQgLALgPAAQgVAAgNgQgARUC5QgQAAgLgKQgLgJAAgPIAAjrQAAgOALgKQALgJAQAAQARAAALAJQALAKAAAOIAADKIBMAAQAQAAALAKQAMAJAAAOQAAAPgMAJQgLAKgQAAgABkCvQgLgKAAgOIAAjrQAAgOALgKQALgJARAAIA8AAQAsAAAdAaQAdAbAAAoQAAArgcAaQgcAbguAAIgWAAIAABPQAAAOgLAKQgLAKgQAAQgRAAgLgKgACmAFIAWAAQAYAAAAgdQAAgbgYAAIgWAAgAgHCcIgKggIhXAAIgJAgQgKAdgcAAQgPAAgLgLQgLgMAAgPQAAgGADgKQA0ijAghBQAKgUAgAAQAeAAAKAUQAaA3A5CtQADAKAAAGQAAAPgLAMQgLALgPAAQgcAAgJgdgAgnA6IgVg9IgVA9IAqAAgAkFCpQgwg8gegbIAABFQAAAOgLAKQgLAKgRAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQARAAALAJQALAKAAAOIAAA0IA+hDQASgSASAAQAPAAALAKQAJALAAAOQAAAQgOAOIhQBMQA+AyAlAyQAKANAAAMQAAAPgKAKQgLALgPAAQgVAAgNgQgAoQCvQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQARAAALAJQAKAKAAAOIAADrQAAAOgLAKQgLAKgQAAQgQAAgLgKgAp/CpQgwg8gegbIAABFQAAAOgLAKQgLAKgQAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAAA0IA/hDQARgSATAAQAPAAAKAKQAKALAAAOQAAAQgPAOIhQBMQA/AyAkAyQAKANAAAMQAAAPgKAKQgKALgPAAQgWAAgNgQgAvRCcIgKggIhXAAIgKAgQgJAdgdAAQgPAAgLgLQgLgMAAgPQAAgGADgKQA0ijAhhBQAJgUAgAAQAeAAAKAUQAcA3A5CtQADAKAAAGQAAAPgLAMQgLALgQAAQgcAAgJgdgAvyA6IgUg9IgWA9IAqAAgAzcCvQgLgKAAgOIAAhbIhIAAIAABbQAAAOgLAKQgLAKgQAAQgQAAgLgKQgLgKAAgOIAAjrQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAABOIBIAAIAAhOQAAgOALgKQALgJAQAAQARAAAKAJQALAKAAAOIAADrQAAAOgLAKQgKAKgRAAQgQAAgLgKgA40C5QgRAAgKgKQgLgJAAgPIAAjsQAAgOALgJQAKgJARAAIBuAAQAQAAAJAJQAKAJAAAOQAAAPgKAKQgJAJgQAAIhIAAIAAAvIBBAAQAQAAAJAJQAKAJAAAOQAAAPgKAKQgJAJgQAAIhBAAIAAA4IBPAAQARAAAJAKQAKAJAAAOQAAAPgKAJQgJAKgRAAgA60C5QgUAAgNgMQgQgQgcg4Igbg5IAABrQAAAOgLAKQgLAKgQAAQgQAAgLgKQgLgKAAgOIAAjmQAAgPAKgMQALgLARAAIAFAAQAWAAAOAOQALAKAPAeQANAYAdBCIAAhvQAAgOALgKQALgJAQAAQAQAAALAJQALAKAAAOIAADoQAAAPgLALQgLALgQAAgA44iSQgIgIAAgNQAAgTAVgJIBCgcQAKgEALAAQAOAAAIAJQAIAJAAAMQAAATgUAJIhIAeIgQACQgNAAgJgJg");
	this.shape.setTransform(194.1,26.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol14, new cjs.Rectangle(4.4,3.7,379.5,45.6), null);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AghAmQgNgMAAgRIAAgQQAAgSANgMQAOgMATAAQAUAAAOAMQANAMAAASIAAAQQAAARgNAMQgOAMgUAAQgTAAgOgMg");
	this.shape.setTransform(140,50);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#399C99").s().p("AghCvQgOgMAAgSIAAj5IgyAAQgTAAgOgMQgNgMAAgRQAAgSANgMQAOgLATAAIDDAAQAUAAANALQANAMAAASQAAARgNAMQgNAMgUAAIg0AAIAAD5QAAASgNAMQgOAMgTAAQgUAAgNgMg");
	this.shape_1.setTransform(119.6,36.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#399C99").s().p("AggDzQgOgNAAgRIAAkjQAAgRAOgLQANgMATAAQAUAAANAMQAOALAAARIAAEjQAAARgOANQgNAMgUgBQgTABgNgMgAhKiZQgLgLAAgQQAAgYAbgKIBQgjQANgEAOAAQAQAAALALQAKAKAAAPQAAAYgbAKIhXAmIgTADQgRgBgKgKg");
	this.shape_2.setTransform(98.1,29.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#399C99").s().p("AhpCJQgxg3AAhRQAAhRAyg2QA0g3BKAAQA3AAAuAYQAfAQgBAaQABARgNANQgNAMgPABQgRAAgPgKQgbgRggAAQghAAgYAfQgYAgAAAtQABAuAWAeQAWAfAgAAQAbAAAQgHIAAggQAAgPgNAAIgOAAQgTAAgOgLQgMgMAAgRQAAgRAMgMQAOgMATAAIAnAAQAvAAASAQQARAPAAArIAABPQAAAZgaANQg0Aag7AAQhKAAgxg1g");
	this.shape_3.setTransform(72.9,36.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#399C99").s().p("AhGC7QgUAAgNgMQgOgMAAgRIAAkjQAAgSAOgMQANgLAUAAICHAAQATAAAMALQAMALAAATQAAASgMALQgMAMgTAAIhYAAIAAA7IBPAAQAUAAAMALQALALAAASQAAARgLAMQgMAMgUAAIhPAAIAABFIBhAAQAUAAAMAMQAMALAAASQAAASgMALQgMAMgUAAg");
	this.shape_4.setTransform(43.6,36.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#399C99").s().p("AhqCZQgTgPAAgUQAAgRAMgNQAMgNATgBQAPAAATAOQAbAUAQAAQAkAAgBgjQABgOgYgMIgygYQhLgkAAhFQAAguAkgfQAkgeAzAAQA2AAAoAfQATAPAAAUQAAASgNANQgNANgSAAQgQAAgOgLQgYgRgPAAQgMAAgHAHQgIAHAAALQAAANAXAMIAyAXQBMAjAABIQgBA0gkAgQgmAhg5AAQg3AAguglg");
	this.shape_5.setTransform(15.5,36.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol13, new cjs.Rectangle(0,0,148.9,71.4), null);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AhqCZQgTgPAAgUQAAgRAMgNQAMgNATgBQAPAAATAOQAbAUAQAAQAkAAgBgjQABgOgYgMIgygYQhLgkAAhFQAAguAkgfQAkgeAzAAQA2AAAoAfQATAPAAAUQAAASgNANQgNANgSAAQgQAAgOgLQgYgRgPAAQgMAAgHAHQgIAHAAALQAAANAXAMIAyAXQBMAjAABIQgBA0gkAgQgmAhg5AAQg3AAguglg");
	this.shape.setTransform(189.2,36.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#399C99").s().p("AghCvQgNgMAAgSIAAkiQAAgRANgMQAOgMATAAQAUAAAOAMQANAMAAARIAAEiQAAASgNAMQgOAMgUAAQgTAAgOgMg");
	this.shape_1.setTransform(168.2,36.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#399C99").s().p("ABVC7QgZAAgQgPQgUgSghhHIgihGIAACEQAAASgNAMQgOAMgUAAQgTAAgOgMQgOgMAAgSIAAkcQAAgTANgNQAOgPAUAAIAHAAQAbAAARASQAOAMATAlQAPAeAiBSIAAiJQAAgSAOgMQAOgMATAAQAVAAANAMQAOAMAAASIAAEeQAAASgOANQgNAOgVAAg");
	this.shape_2.setTransform(132.9,36.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#399C99").s().p("AhGC7QgUAAgNgMQgOgMAAgRIAAkjQAAgSAOgMQANgLAUAAICHAAQATAAAMALQAMALAAATQAAASgMALQgMAMgTAAIhYAAIAAA7IBPAAQAUAAAMALQALALAAASQAAARgLAMQgMAMgUAAIhPAAIAABFIBhAAQAUAAAMAMQAMALAAASQAAASgMALQgMAMgUAAg");
	this.shape_3.setTransform(103.3,36.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#399C99").s().p("AhQC7QgVAAgNgMQgOgMAAgSIAAkiQAAgSAOgMQAMgLAVAAIA9AAQBAAAAkAcQAjAdAAA0QAAAoghAZQAVAMAOAXQAMAXAAAZQAAA4gmAeQgnAehIAAgAgiBpIAOAAQA1AAAAgiQAAgggnAAIgcAAgAgigqIAXAAQAeAAABgfQAAgSgKgGQgJgHgXAAIgMAAg");
	this.shape_4.setTransform(74.9,36.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#399C99").s().p("AhRC7QgTAAgOgMQgOgMAAgSIAAkiQAAgSAOgMQANgLATAAIA+AAQBAAAAjAcQAkAdAAA0QAAAogiAZQAWAMANAXQANAXAAAZQAAA4gnAeQgmAehIAAgAgiBpIAOAAQA1AAAAgiQABgggoAAIgcAAgAgigqIAXAAQAfAAAAgfQAAgSgKgGQgJgHgWAAIgNAAg");
	this.shape_5.setTransform(45.4,36.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#399C99").s().p("AhGC7QgUAAgNgMQgOgMAAgRIAAkjQAAgSAOgMQANgLAUAAICHAAQATAAAMALQAMALAAATQAAASgMALQgMAMgTAAIhYAAIAAA7IBPAAQAUAAAMALQALALAAASQAAARgLAMQgMAMgUAAIhPAAIAABFIBhAAQAUAAAMAMQAMALAAASQAAASgMALQgMAMgUAAg");
	this.shape_6.setTransform(16.7,36.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(0,0,204.9,71.4), null);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#399C99").s().p("AhqCZQgTgPgBgUQAAgRANgNQAMgNATgBQAPAAATAOQAbAUARAAQAjAAAAgjQAAgOgYgMIgygYQhLgkAAhFQAAguAkgfQAkgeAzAAQA2AAAoAfQASAPABAUQAAASgNANQgNANgRAAQgRAAgPgLQgXgRgPAAQgLAAgIAHQgIAHAAALQAAANAXAMIAyAXQBMAjAABIQAAA0gmAgQgkAhg5AAQg4AAguglg");
	this.shape.setTransform(351.5,36.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#399C99").s().p("AhqCZQgUgPABgUQgBgRANgNQANgNASgBQAPAAATAOQAbAUAQAAQAjAAAAgjQAAgOgXgMIgygYQhLgkAAhFQAAguAkgfQAkgeAzAAQA2AAAoAfQASAPAAAUQAAASgMANQgMANgTAAQgQAAgOgLQgYgRgPAAQgMAAgHAHQgIAHAAALQAAANAWAMIA0AXQBKAjAABIQABA0gmAgQgkAhg6AAQg3AAguglg");
	this.shape_1.setTransform(324.5,36.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#399C99").s().p("AhGC7QgUAAgNgMQgOgMAAgRIAAkjQAAgSAOgMQANgLAUAAICHAAQATAAAMALQAMALAAATQAAASgMALQgMAMgTAAIhYAAIAAA7IBPAAQAUAAAMALQALALAAASQAAARgLAMQgMAMgUAAIhPAAIAABFIBhAAQAUAAAMAMQAMALAAASQAAASgMALQgMAMgUAAg");
	this.shape_2.setTransform(298.1,36.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#399C99").s().p("ABVC7QgZAAgQgPQgUgSghhHIgihGIAACEQAAASgNAMQgOAMgUAAQgTAAgOgMQgOgMAAgSIAAkcQAAgTANgNQAOgPAUAAIAHAAQAbAAARASQAOAMATAlQAPAeAiBSIAAiJQAAgSAOgMQAOgMATAAQAVAAANAMQAOAMAAASIAAEeQAAASgOANQgNAOgVAAg");
	this.shape_3.setTransform(266.8,36.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#399C99").s().p("AggCvQgOgMAAgSIAAkiQAAgRAOgMQANgMATAAQAUAAANAMQAOAMAAARIAAEiQAAASgOAMQgOAMgTAAQgTAAgNgMg");
	this.shape_4.setTransform(242.6,36.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#399C99").s().p("AhqCZQgTgPAAgUQAAgRAMgNQANgNASgBQAPAAATAOQAbAUAQAAQAkAAAAgjQAAgOgYgMIgygYQhLgkAAhFQAAguAkgfQAkgeAzAAQA2AAAoAfQASAPABAUQAAASgNANQgNANgRAAQgRAAgPgLQgXgRgPAAQgLAAgIAHQgIAHAAALQAAANAXAMIAyAXQBMAjAABIQgBA0gkAgQgmAhg5AAQg3AAguglg");
	this.shape_5.setTransform(221.5,36.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#399C99").s().p("AhkCYQglglAAg9IAAjJQgBgRAOgMQAOgMAUAAQAUAAANAMQANAMAAARIAADIQAAA1AsAAQAsAAAAg1IAAjIQAAgRAOgMQAOgMATAAQAVAAANAMQAOAMAAARIAADJQAAA9gnAlQglAlg/AAQg+AAgmglg");
	this.shape_6.setTransform(191.9,36.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#399C99").s().p("AhQC7QgVAAgNgMQgOgMAAgSIAAkiQAAgSANgMQANgLAVAAIA+AAQA/AAAkAcQAjAdAAA0QAAAogiAZQAXAMANAXQAMAXAAAZQAAA4gmAeQgnAehHAAgAgiBpIAPAAQA1AAAAgiQAAgggpAAIgbAAgAgigqIAXAAQAeAAAAgfQAAgSgJgGQgJgHgXAAIgMAAg");
	this.shape_7.setTransform(162,36.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#399C99").s().p("AhoCIQgxg3AAhQQAAhRAyg2QAzg3BLAAQAoAAAjAMQAZAJANAKQASAQAAATQAAARgMAMQgMANgSABQgRAAgQgMQgWgPgiAAQgiAAgXAfQgYAfAAAuQAAAtAXAfQAWAfAfAAQAcAAAhgSQAOgJAPAAQASAAAMAMQANAMAAATQAAAZgZAOQg1Abg3AAQhJAAgxg2g");
	this.shape_8.setTransform(119.3,36.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#399C99").s().p("AhtCvQgOgMAAgSIAAkhQAAgSAOgMQAOgMAUAAIBLAAQA0AAAkAhQAkAgAAAzQAAA1gjAgQgiAgg3AAIgdAAIAABiQAAASgNAMQgNAMgUAAQgUAAgOgMgAgdgiIAdAAQAcABAAglQAAgigcAAIgdAAg");
	this.shape_9.setTransform(91.6,36.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#399C99").s().p("AhkCYQglglAAg9IAAjJQAAgRANgMQAOgMAUAAQAUAAANAMQANAMAAARIAADIQAAA1AsAAQAsAAAAg1IAAjIQAAgRAOgMQAOgMATAAQAVAAANAMQANAMAAARIAADJQAAA9gmAlQglAlg/AAQg+AAgmglg");
	this.shape_10.setTransform(59.9,36.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#399C99").s().p("ABBCYIgMgoIhqAAIgMAoQgMAjgjAAQgTAAgNgOQgNgOAAgTQAAgIADgLQBAjKAohQQAMgZAmAAQAmAAAMAZQAiBEBGDWQAEALAAAIQAAATgNAOQgOAOgTAAQgjAAgMgjgAAaAeIgahLIgZBLIAzAAg");
	this.shape_11.setTransform(17.4,36.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol11, new cjs.Rectangle(0,0,367.1,71.4), null);


(lib.priceBadge = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhPBoQgdgmAAhBQAAhAAegnQAdgmAxAAQAyAAAdAmQAeAnAABAQAABBgdAmQgdAlgzAAQgyAAgdglgAgag5QgLAXAAAjQAAAkALAWQAKAVAQAAQAQAAALgVQALgWAAgkQAAgjgLgXQgLgWgQgBQgPABgLAWg");
	this.shape.setTransform(25.4,8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAFCCQgKgJAAgNIAAicIgKAGQgJAFgIAAQgOAAgJgJQgIgJAAgNQAAgTAPgKIA3giQALgHALAAQAPAAAKAJQAKAJAAANIAADXQAAANgKAJQgKAJgPAAQgOAAgKgJg");
	this.shape_1.setTransform(6,8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhVBWQgOgfAAgpQAAiaBsAAQAuAAAYAWQAMAMAAAOQAAANgKAJQgJAJgPAAQgKAAgOgLQgLgHgNgBQgZAAgIAoQAUgJAQAAQAogBAZAdQAXAZAAAmQAAArgbAcQgbAcgsAAQg+AAgZg3gAgQATQgHAJAAAOQAAARAHAKQAHALALAAQAMAAAIgLQAHgKAAgRQAAgOgHgJQgIgJgMAAQgLAAgHAJg");
	this.shape_2.setTransform(-11.3,8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAOCCQgKgJAAgNIAAgeIhNAAQgPAAgLgIQgJgJgBgNQABgLAFgKQAjhGBEhMQARgTASAAQAOAAAKAJQAJAJAAANQABANgNANQg0A1gdAtIAdAAIAAgTQAAgOAKgIQAKgJAPAAQAPAAAKAJQAJAIABAOIAAATIABAAQAPAAAKAJQAJAJABANQgBANgJAJQgKAIgPAAIgBAAIAAAeQgBANgJAJQgKAJgPAAQgPAAgKgJg");
	this.shape_3.setTransform(-32.8,8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAJAWIgJgMIgIAMQgCADgCAAQgFAAAAgFQAAgCACgDIAIgKIgNgFQgFgBAAgDQAAgGAFAAIAFABIALAFIAAgPQAAgFAEAAQAFAAAAAFIAAAPIALgFIAFgBQAFAAAAAGQAAADgFABIgMAFIAHAKQADADAAACQAAAFgFAAQgDAAgCgDg");
	this.shape_4.setTransform(23.8,32.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgHBGQgFgDgCgHQgBgHAAgPIAAhpQAAgIAHAAQAHAAAAAIIAABpQAAAPACAEQABAFAIAAQAGAAABAHQgBAHgIAAQgKAAgFgGg");
	this.shape_5.setTransform(17.4,37.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfA9QgNgPAAgXQAAgXANgOQAMgOATAAQAUAAAMAOQAMAOAAAXQABAYgMAOQgNAOgUAAQgTAAgMgOgAgUgEQgJAKABARQgBARAJALQAHAKANAAQAOAAAIgKQAHgKAAgSQAAgSgHgJQgIgKgOAAQgNAAgHAKgAgQg0QAAgFAFgCIAfgOIAFgBQAIAAAAAGQAAAFgGACIgeAOIgGACQgGAAgBgHg");
	this.shape_6.setTransform(9.6,37.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIA8QgLgJAAgXIAAgxIgJAAQgHAAAAgHQAAgHAHAAIAJAAIAAgXQAAgIAHAAQAIAAAAAIIAAAXIAZAAQAGAAAAAHQAAAHgGAAIgZAAIAAAxQgBAYAVAAIAIgBIAGgCQAGAAAAAHQAAAGgIADQgGACgGAAQgQAAgIgHg");
	this.shape_7.setTransform(1.2,38.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgXAHQgIAAAAgHQAAgGAIAAIAwAAQAHAAAAAGQAAAHgHAAg");
	this.shape_8.setTransform(-7.1,39.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIA8QgLgJAAgXIAAgxIgJAAQgHAAAAgHQAAgHAHAAIAJAAIAAgXQAAgIAHAAQAIAAAAAIIAAAXIAZAAQAGAAAAAHQAAAHgGAAIgZAAIAAAxQAAAYATAAIAIgBIAHgCQAGAAAAAHQAAAGgIADQgFACgHAAQgQAAgIgHg");
	this.shape_9.setTransform(-15.4,38.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjA/IAAh7QAAgKAKAAIA2AAQAHAAAAAHQAAAHgHAAIgyAAIAAAuIAuAAQAIAAgBAHQABAGgIAAIguAAIAAA8QAAAIgGAAQgIAAAAgIg");
	this.shape_10.setTransform(-23.1,37.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggBAQgNgPAAgZQAAgYANgOQAMgPAUAAQAVAAAMAPQANAOAAAYQAAAZgMAPQgNAPgVAAQgUAAgMgPgAgVgEQgJAKAAASQAAASAJALQAIALANAAQAOAAAJgLQAIgKAAgTQAAgSgJgKQgIgLgOAAQgNAAgIALgAgQg2QAAgFAFgDIAhgOIAFgCQAHAAAAAHQAAAFgFADIghAOIgFACQgHAAAAgHg");
	this.shape_11.setTransform(17.2,-21.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA/QgMgKAAgYIAAgzIgJAAQgIAAABgIQgBgHAIAAIAJAAIAAgYQAAgIAHAAQAJAAgBAIIAAAYIAaAAQAIAAAAAHQAAAIgIAAIgaAAIAAAzQAAAaAVAAIAIgCIAHgBQAGAAABAHQAAAGgJADQgFACgHAAQgRAAgIgHg");
	this.shape_12.setTransform(8.3,-20.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIA/QgMgKAAgYIAAgzIgJAAQgHAAgBgIQABgHAHAAIAJAAIAAgYQAAgIAIAAQAHAAABAIIAAAYIAaAAQAHAAAAAHQAAAIgHAAIgaAAIAAAzQAAAaAUAAIAJgCIAGgBQAHAAgBAHQAAAGgIADQgGACgGAAQgRAAgIgHg");
	this.shape_13.setTransform(1.1,-20.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAtQgJgJAAgVIAAg8QAAgIAIAAQAHAAAAAIIAAA5QAAAQAGAFQAFAGAOAAQAOAAAKgJIAAhLQAAgIAHAAQAIAAAAAIIAABaQAAAHgHAAQgHAAAAgHIAAgBQgMAKgPAAQgVAAgIgJg");
	this.shape_14.setTransform(-7.8,-19);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgdAuIAAhaQAAgHAIAAQAHAAAAAHIAAAJQACgGAHgGQAIgGAKAAIAKABQAHACAAAGQAAAHgHAAIgKgBQgKAAgGAHQgLAMAAAYIAAApQAAAIgHAAQgIAAAAgIg");
	this.shape_15.setTransform(-16,-19.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AglBHQgFgDAAgHIAAiEQAAgIAHAAQAIAAAAAIIAAAwQAKgFANAAQAVAAANAOQANAOAAAZQAAAYgNAPQgOAQgUAAQgUAAgNgJgAgbgHIAABDQALAFAMAAQAPAAAJgNQAIgLAAgQQAAgSgJgKQgJgLgOAAQgNAAgKAHg");
	this.shape_16.setTransform(-25.1,-21.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgGBDIAAhaQAAgIAGAAQAIAAgBAIIAABaQABAHgIAAQgGAAAAgHgAgGg6IAAgIQAAgIAGAAQAIAAgBAIIAAAIQABAHgIAAQgGAAAAgHg");
	this.shape_17.setTransform(29.8,-41.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgKAuQgKgSgYhFIgBgEQgBgHAIAAQAFAAACAFQASA0ANAfQANgfASg0QACgFAGAAQAHAAAAAGIAAAFQgaBFgJASQgEAHgHAAQgHAAgDgHg");
	this.shape_18.setTransform(23.3,-39.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgfAvQgLgJAAgRQAAgiA2AAIAHAAIAAgIQAAgSgUAAQgKAAgIADIgLAEQgHAAAAgHQAAgGAHgDQAOgFAPAAQAQgBAKAJQAKAJAAAPIAAAyQAAAGAEAEQAEACAAAFQAAAHgHAAQgIAAgFgIQgLAKgRAAQgPgBgLgHgAgbAVQAAAJAHAGQAGADAKAAQAQAAAHgHIAAgfIgHAAQgnAAAAAUg");
	this.shape_19.setTransform(14,-39.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAYBIIAAg8QAAgOgFgFQgFgGgOAAQgMAAgMAHIAABOQAAAHgHAAQgIAAAAgHIAAiOQAAgIAIAAQAHAAAAAIIAAAxQANgGANAAQAWgBAJALQAHAJAAATIAAA9QAAAHgHAAQgJAAAAgHg");
	this.shape_20.setTransform(3.9,-42.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgdAuIAAhaQAAgHAIAAQAHAAAAAHIAAAJQACgGAHgGQAIgGAKAAIAKABQAHACAAAGQAAAHgHAAIgKgBQgKAAgGAHQgLAMAAAYIAAApQAAAIgHAAQgIAAAAgIg");
	this.shape_21.setTransform(-8.8,-39.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgfBHQgLgJAAgQQAAgjA2AAIAHAAIAAgIQAAgSgUAAQgKAAgIADIgLAEQgHAAAAgHQAAgFAHgDQAOgGAPAAQAQAAAKAIQAKAJAAAPIAAAyQAAAHAEADQAEADAAAEQAAAHgHAAQgIAAgFgIQgLAKgRAAQgPAAgLgIgAgbAuQAAAJAHAFQAGAEAKAAQAQAAAHgIIAAgfIgHAAQgnAAAAAVgAgYg2QAAgFAFgDIAhgOIAFgCQAIAAAAAHQAAAFgFADIghAOIgGACQgHAAAAgHg");
	this.shape_22.setTransform(-17.7,-41.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AA8BCIgNh1QgPAmgWBKQgDAJgHAAQgGAAgDgJQgWhKgPgmIgNB1QgBAIgHAAQgHAAAAgHIABgHIANh7QABgKAJAAQAHAAAEAGQAJANAeBiQAfhiAIgMQAFgHAHAAQAJAAABAKIANB7IABAGQAAAIgHAAQgHAAgBgIg");
	this.shape_23.setTransform(-31.4,-41.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#D9425C").s().p("An5H5QjRjRAAkoQAAknDRjRQDSjSEnAAQEoAADRDSQDSDRAAEnQAAEojSDRQjRDSkoAAQknAAjSjSg");
	this.shape_24.setTransform(0,0,1.021,1.021);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.priceBadge, new cjs.Rectangle(-73,-73,146,146), null);


(lib.logoVodafone = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhdCRQgtgtAAhFQAAgsAWgtQAVgqAigcQAggaAogPQApgQAnAAQANAAAFACQgiAHgYAdQgYAdAAAkIAAAEQBxAcAABkQgBA0gjAoQgoAsg9AAQg3AAgpgpg");
	this.shape.setTransform(0.1,-3.4,0.773,0.773);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F1001B").s().p("Ai0C1QhLhLAAhqQAAhpBLhLQBLhLBpAAQBqAABLBLQBLBLAABpQAABqhLBLQhLBLhqAAQhpAAhLhLg");
	this.shape_1.setTransform(0,0,0.773,0.773);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoVodafone, new cjs.Rectangle(-19.8,-19.8,39.6,39.6), null);


(lib.logoUpc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA5B9IAAg0IAIAAIAAAEQAEgFAHAAQAHAAAEAFQAEAFAAAIQAAAIgEAFQgEAGgHAAQgHAAgEgEIAAAUgABABaQAAAMAKAAQAKAAAAgMQAAgLgKAAQgKAAAAALgABkBoQgFgGAAgIQAAgSATAAQAJAAAFAIIgFAEQgFgFgFAAQgKAAAAAMQAAAFADADQADADAEAAQAHAAAEgGIAFAFQgHAIgJAAQgIAAgFgFgAAUBgIAAgXIAIAAIAAAVQAAAHAGAAQAJAAAAgJIAAgTIAIAAIAAAjIgHAAIAAgFQgFAFgGAAQgNAAAAgMgAg5BFQgFgDAAgCQgNgBgMgFQgIgDgEgEQgGgFAEAAQADAAAQAFIABAAIgCgBQgRgGgMgLQgMgLACgEQABgDASAPIABAAIgBgBQgNgKgIgSQgGgPADgDQABAAAJAPIAGAKIABAAIAAAAQgPgdgBgdQgBgOACgDQACgEABAGIAFAcQAEAWAIASIAIAVIAFAJQABAAABABQAAAAABAAQAAABAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAQAAgBgBAAQgHgOgDgJIgGgWIgBgMIABgMIABgMIAEgLQAEgGADgBIACgBIAAgBIACAAIADABIAEAEIADAEIAKAWIAEAMIAGAXIABABQgEAEgCAHIgFASIgCARQAAAAAAABQAAAAAAABQABAAAAAAQAAAAABAAIABAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAgBAAAAIABgIIACgIQABgJAEgIQADgJAFgEIAFgFQADgBAEAAIAGABIAGAFQAEAEAEAJIAFARIACAQQAAAAABABQAAAAAAABQAAAAAAAAQABAAAAAAIAAAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAgBAAAAIgBgRIgFgSQgDgHgDgEIAAgBIAPguIAEgLIADgEIAEgEIAEgBIABAAIABABIACABQADACADAFIAEALIACAMQABAGgBAGIgDAYIgEAKQgEANgGAKQAAAAAAABQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAAAIALgVIADgJQAIgTADgVIAFgcQACgGABAEQACADgBAOQAAAZgPAhIAHgKQAIgQABABQAEADgHAPQgIASgMAKIgBABIAAAAIAMgJQAHgFABACQABAFgLAKQgNALgRAGIgCABIACAAIASgFQAEAAgGAFQgDAEgJADQgKAFgNABQgBACgFADQgHADgLAAQgLAAgIgDgAgdgLQgEgDgFAAQgFAAgFADIgGAFQgGgagHgSIgDgIIAEgUQACgOAGgMQAIgUAMAAQARAAALAuIADAUIgDAIQgHASgGAagAAggkQAAgHgBgGQgBgHgDgFIgDgGIgFgFIgCgBIgCgBIABgaQgBgPADAAQADAAAGAPQAGASACAUQABAOgDATIgBAJgAhvgdQgDgQACgRQABgUAHgSQAFgPAEAAQACAAAAAPQgBAOABAMIgCABIgBABIgGAFIgDAGIgEAMIgBAdgAgMhnQAFAAAFAKQAEAKACAKIgBABIgGAHQgEgXgFgPgAhRhIIgBgBQACgLAFgJQAGgKAFAAQgGAOgEAYQgDgFgEgCg");
	this.shape.setTransform(3.1,1.9,0.773,0.773);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009B98").s().p("Ai1C2QhKhMAAhqQAAhpBKhMQBMhKBpgBQBqABBLBKQBMBMAABpQAABqhMBMQhLBKhqAAQhpAAhMhKg");
	this.shape_1.setTransform(0,0,0.773,0.773);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoUpc, new cjs.Rectangle(-19.8,-19.8,39.7,39.7), null);


(lib.logoPlus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F1001B").s().p("AglAGIAAgLIBLAAIAAALg");
	this.shape.setTransform(0,0,0.773,0.773);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F1001B").s().p("AgFArIAAhVIALAAIAABVg");
	this.shape_1.setTransform(0,0,0.773,0.773);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logoPlus, new cjs.Rectangle(-2.9,-3.3,5.9,6.7), null);


(lib.btnArrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1.5,1,1).p("AgwhiIBhBiIhhBj");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btnArrow, new cjs.Rectangle(-5.9,-10.8,11.9,21.8), null);


(lib.bgImg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Bitmap 7
	this.instance = new lib.nehaBg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bgImg, new cjs.Rectangle(0,0,1067,275.1), null);


(lib.megbizhatoTxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol16();
	this.instance.parent = this;
	this.instance.setTransform(170.1,143.5,1,1,0,0,0,153.3,29.3);

	this.instance_1 = new lib.Symbol15();
	this.instance_1.parent = this;
	this.instance_1.setTransform(138.3,93.9,1,1,0,0,0,121.5,29.3);

	this.instance_2 = new lib.Symbol14();
	this.instance_2.parent = this;
	this.instance_2.setTransform(211,44.3,1,1,0,0,0,194.2,29.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.megbizhatoTxt, new cjs.Rectangle(21.2,18.7,379.5,140.7), null);


(lib.erdeklodjonTxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol22();
	this.instance.parent = this;
	this.instance.setTransform(233.4,17.1,1,1,0,0,0,48.5,17.1);

	this.instance_1 = new lib.Symbol21();
	this.instance_1.parent = this;
	this.instance_1.setTransform(153.5,17.1,1,1,0,0,0,30.7,17.1);

	this.instance_2 = new lib.Symbol20();
	this.instance_2.parent = this;
	this.instance_2.setTransform(61,17.1,1,1,0,0,0,61,17.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.erdeklodjonTxt, new cjs.Rectangle(0,0,281.8,34.2), null);


(lib.erdekelBtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btnArrow
	this.btnArrow = new lib.btnArrow();
	this.btnArrow.name = "btnArrow";
	this.btnArrow.parent = this;
	this.btnArrow.setTransform(44.1,0.5);

	this.timeline.addTween(cjs.Tween.get(this.btnArrow).wait(1));

	// Érdekel
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBQQgHgKAAgbIAAh3QAAgGADgDQADgEAGAAQAFAAADAEQACADAAAGIAAB3QAAAPADAFQACAEAFAAQALAAAAALQAAALgLAAQgSAAgHgJg");
	this.shape.setTransform(23.5,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgjAtQgPgRAAgcQAAgbAPgRQAPgSAYAAQAVAAANANQAMALAAANQAAAWgUAIQgSAHglABQAGAbAWAAQAIAAAXgJIAGgBQAEAAAEAEQADADAAAEQAAAHgGADQgVAMgVAAQgXAAgPgSgAgZgHQAzgCAAgQQAAgFgFgEQgGgFgLAAQgZAAgEAgg");
	this.shape_1.setTransform(13.5,2.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaBVQgYgjgWgQIgCAAIAAAsQAAAFgEADQgCAEgGgBQgFABgDgEQgDgDAAgFIAAiaQAAgGADgDQADgEAFAAQAGAAACAEQAEADAAAGIAABUIAlglQADgDAGAAQAFAAADADQADAEAAAFQAAAFgDAEIggAgQAWAQAWAiQACADAAAEQABAFgEADQgEAEgEgBQgGAAgDgEg");
	this.shape_2.setTransform(2.8,-0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgjAtQgPgRAAgcQAAgbAPgRQAPgSAYAAQAVAAANANQAMALAAANQAAAWgUAIQgSAHglABQAGAbAWAAQAIAAAXgJIAGgBQAEAAAEAEQADADAAAEQAAAHgGADQgVAMgVAAQgXAAgPgSgAgZgHQAzgCAAgQQAAgFgFgEQgGgFgLAAQgZAAgEAgg");
	this.shape_3.setTransform(-9.6,2.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBJQgQgSAAgcQAAgbAPgRQAQgRAYAAQANAAAKAFIAAgxQAAgLALAAQAMAAAAALIAACQQADAAACABQAFAEAAAGQAAAFgDADQgEAEgFAAQgJAAgGgHQgPAIgNAAQgYAAgQgRgAgWgBQgJAKAAASQAAAQAIAMQAJANAPAAQAJAAANgGIAAhEQgOgGgJAAQgNAAgJALg");
	this.shape_4.setTransform(-21.9,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggA6QgDgCAAgGIAAhiQAAgMAMAAQALAAAAAMIAAADQAKgQAQAAQAPAAAFAGQACADAAADQAAAGgDADQgDAEgFAAIgDgBIgIgCQgKAAgFAIQgLALAAAZIAAAtQAAAGgDACQgDAEgFAAQgGAAgDgEg");
	this.shape_5.setTransform(-32.1,2.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiByQgMAAAAgMIAAiQQAAgKAMgBIBAAAQAMABAAAKQAAAMgMAAIg1AAIAAAtIAxAAQAMAAAAALQAAALgMAAIgxAAIAAA2IA6AAQAMABAAAKQAAAMgMAAgAgchNQgDgEAAgEQAAgHAIgEIAogRIAEAAQAEAAAEADQADADAAAFQAAAHgIAEIgoAQIgEABQgEAAgEgDg");
	this.shape_6.setTransform(-43.4,-2.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_4
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#EE742C").s().p("ApSC+Qg8AAAAg8IAAkDQAAg8A8AAISlAAQA8AAAAA8IAAEDQAAA8g8AAg");
	this.shape_7.setTransform(0,0,1,1.001);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

}).prototype = getMCSymbolPrototype(lib.erdekelBtn, new cjs.Rectangle(-65.5,-19,131,38), null);


(lib.azInternetbenTxtcopy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol 4
	this.instance = new lib.Symbol13();
	this.instance.parent = this;
	this.instance.setTransform(74.4,156.9,1,1,0,0,0,74.4,35.7);

	this.instance_1 = new lib.Symbol12();
	this.instance_1.parent = this;
	this.instance_1.setTransform(102.4,94.5,1,1,0,0,0,102.4,35.7);

	this.instance_2 = new lib.Symbol11();
	this.instance_2.parent = this;
	this.instance_2.setTransform(183.6,32.1,1,1,0,0,0,183.6,35.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.azInternetbenTxtcopy, new cjs.Rectangle(0,-3.6,367.1,196.2), null);


(lib.azInternetbenTxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol 4
	this.instance = new lib.Symbol19();
	this.instance.parent = this;
	this.instance.setTransform(127.5,144.1,1,1,0,0,0,88.8,15.2);

	this.instance_1 = new lib.Symbol18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(165.2,89.8,1,1,0,0,0,128.2,20.1);

	this.instance_2 = new lib.Symbol17();
	this.instance_2.parent = this;
	this.instance_2.setTransform(164.2,41.6,1,1,0,0,0,126.6,22.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.azInternetbenTxt, new cjs.Rectangle(37,18.8,256.5,140.5), null);


(lib.Banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// vodafoneCegcsoport
	this.vodafoneCegcsoport = new lib.vodafoneCegcsoport();
	this.vodafoneCegcsoport.name = "vodafoneCegcsoport";
	this.vodafoneCegcsoport.parent = this;
	this.vodafoneCegcsoport.setTransform(903.3,233.1);

	this.timeline.addTween(cjs.Tween.get(this.vodafoneCegcsoport).wait(1));

	// upcLogo
	this.upcLogo = new lib.logoUpc();
	this.upcLogo.name = "upcLogo";
	this.upcLogo.parent = this;
	this.upcLogo.setTransform(930.4,198.3);

	this.timeline.addTween(cjs.Tween.get(this.upcLogo).wait(1));

	// vodafoneLogo
	this.vodafoneLogo = new lib.logoVodafone();
	this.vodafoneLogo.name = "vodafoneLogo";
	this.vodafoneLogo.parent = this;
	this.vodafoneLogo.setTransform(876.3,198.3);

	this.timeline.addTween(cjs.Tween.get(this.vodafoneLogo).wait(1));

	// logoPlus
	this.logoPlus = new lib.logoPlus();
	this.logoPlus.name = "logoPlus";
	this.logoPlus.parent = this;
	this.logoPlus.setTransform(903.4,198.3);

	this.timeline.addTween(cjs.Tween.get(this.logoPlus).wait(1));

	// Layer_13
	this.erdeklodjonTxt = new lib.erdeklodjonTxt();
	this.erdeklodjonTxt.name = "erdeklodjonTxt";
	this.erdeklodjonTxt.parent = this;
	this.erdeklodjonTxt.setTransform(162.7,211,1,1,0,0,0,140.9,17.1);

	this.timeline.addTween(cjs.Tween.get(this.erdeklodjonTxt).wait(1));

	// whiteBar
	this.whiteBar = new lib.whiteBar();
	this.whiteBar.name = "whiteBar";
	this.whiteBar.parent = this;
	this.whiteBar.setTransform(0,169);

	this.timeline.addTween(cjs.Tween.get(this.whiteBar).wait(1));

	// priceBadge
	this.priceBadge = new lib.priceBadge();
	this.priceBadge.name = "priceBadge";
	this.priceBadge.parent = this;
	this.priceBadge.setTransform(453.1,105);

	this.timeline.addTween(cjs.Tween.get(this.priceBadge).wait(1));

	// erdekelBtn
	this.erdekelBtn = new lib.erdekelBtn();
	this.erdekelBtn.name = "erdekelBtn";
	this.erdekelBtn.parent = this;
	this.erdekelBtn.setTransform(890,73);

	this.timeline.addTween(cjs.Tween.get(this.erdekelBtn).wait(1));

	// aUpcEbbenIsTxt
	this.aUpcEbbenIsTxt = new lib.azInternetbenTxtcopy();
	this.aUpcEbbenIsTxt.name = "aUpcEbbenIsTxt";
	this.aUpcEbbenIsTxt.parent = this;
	this.aUpcEbbenIsTxt.setTransform(177.2,114.7,1,1,0,0,0,147.1,88.4);

	this.timeline.addTween(cjs.Tween.get(this.aUpcEbbenIsTxt).wait(1));

	// alapjaratonTxt
	this.megbizhatoTxt = new lib.azInternetbenTxt();
	this.megbizhatoTxt.name = "megbizhatoTxt";
	this.megbizhatoTxt.parent = this;
	this.megbizhatoTxt.setTransform(147.1,88.4,1,1,0,0,0,147.1,88.4);

	this.timeline.addTween(cjs.Tween.get(this.megbizhatoTxt).wait(1));

	// megbizhatoTxt
	this.nehaTxt = new lib.megbizhatoTxt();
	this.nehaTxt.name = "nehaTxt";
	this.nehaTxt.parent = this;
	this.nehaTxt.setTransform(147.1,82.4,1,1,0,0,0,147.1,88.4);

	this.timeline.addTween(cjs.Tween.get(this.nehaTxt).wait(1));

	// whiteEllipse
	this.whiteEllipse = new lib.whiteEllipse();
	this.whiteEllipse.name = "whiteEllipse";
	this.whiteEllipse.parent = this;
	this.whiteEllipse.setTransform(456.7,236.6,1,1,0,0,0,304.2,283.5);

	this.timeline.addTween(cjs.Tween.get(this.whiteEllipse).wait(1));

	// bgImgStart
	this.bgImgStart = new lib.bgImg();
	this.bgImgStart.name = "bgImgStart";
	this.bgImgStart.parent = this;
	this.bgImgStart.setTransform(-60.9,-38,0.987,0.987);

	this.timeline.addTween(cjs.Tween.get(this.bgImgStart).wait(1));

	// bgImg
	this.bgImg = new lib.bgImg();
	this.bgImg.name = "bgImg";
	this.bgImg.parent = this;
	this.bgImg.setTransform(-0.1,-29.1,0.909,0.909,0,0,0,-0.1,-0.1);
	this.bgImg.alpha = 0.762;

	this.timeline.addTween(cjs.Tween.get(this.bgImg).wait(1));

}).prototype = getMCSymbolPrototype(lib.Banner, new cjs.Rectangle(-164.6,-317.6,1156.6,567.7), null);


// stage content:
(lib.upc_b2b_2019_kikapcs_new_970x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(320.4,-192.6,1156.6,567.7);
// library properties:
lib.properties = {
	id: '524E1A33E1DB4A6D85F6C58ACCAEF523',
	width: 970,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/nehaBg.jpg", id:"nehaBg"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['524E1A33E1DB4A6D85F6C58ACCAEF523'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;